[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-yaml" },
  { id = "check-merge-conflict" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace", args = ["--markdown-linebreak-ext=md"] },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.33.1"
hooks = [
  { id = "typos", args = ["--force-exclude"] },
]
